scientists:
  - Albert Einstein
  - Charles Darwin
  - Francis Crick
  - Galileo Galilei
  - Isaac Newton
  - Marie Curie
  - Michael Faraday
  - Rosalind Franklin
  - Stephen Hawking
  - Thomas Edison
actors:
  - Angelina Jolie
  - Brad Pitt
  - Denzel Washington
  - Harrison Ford
  - Jennifer Lawrence
  - Johnny Depp
  - Julia Roberts
  - Leonardo DiCaprio
  - Meryl Streep
  - Nicole Kidman
  - Scarlett Johansson
  - Tom Cruise
  - Tom Hanks
  - Will Smith
fruits:
  - Apple
  - Banana
  - Grape
  - Lemon
  - Orange
  - Strawberry
  - Watermelon
